# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: Compile
on: 
  workflow_dispatch:
    branches:
      - master
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usage
        run: echo ${{ github.event.inputs.version }}

