# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: Compile
on: 
  workflow_dispatch:
    branches:
      - master
jobs:
  compiler:
    name: Compile kernel
    runs-on: ubuntu-latest
    fail-fast: false
    matrix:
      arch: [ARM, ARM_HYP, AARCH64, RISCV64, X64]
      compiler: [gcc, llvm]
      exclude:
        # llvm RISCV64 compilation is not currently supported
        - arch: RISCV64
          compiler: llvm


