# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: Nightly build
on: 
  workflow_dispatch:
jobs:
  nightly-build:
    name: Build it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jourau/ci-actions/nightly-build@master
        with:
          ARCH: AARCH64
          COMPILER: gcc

