# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: Style

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
    - uses: jourau/ci-actions/style@master
